// Code generated by Kitex v0.1.3. DO NOT EDIT.

package resourceusageagent

import (
	"context"
	"github.com/cloudwego/kitex/client"
	"github.com/cloudwego/kitex/client/callopt"
	"github.com/cloudwego/kitex/pkg/streaming"
	"github.com/cloudwego/kitex/transport"
	"github.com/pingcap/kvproto/proto/kitex_gen/resource_usage_agent"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	ReportCPUTime(ctx context.Context, callOptions ...callopt.Option) (stream ResourceUsageAgent_ReportCPUTimeClient, err error)
	Report(ctx context.Context, callOptions ...callopt.Option) (stream ResourceUsageAgent_ReportClient, err error)
}

type ResourceUsageAgent_ReportCPUTimeClient interface {
	streaming.Stream
	Send(*resource_usage_agent.CPUTimeRecord) error
	CloseAndRecv() (*resource_usage_agent.EmptyResponse, error)
}

type ResourceUsageAgent_ReportClient interface {
	streaming.Stream
	Send(*resource_usage_agent.ResourceUsageRecord) error
	CloseAndRecv() (*resource_usage_agent.EmptyResponse, error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, client.WithTransportProtocol(transport.GRPC))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kResourceUsageAgentClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kResourceUsageAgentClient struct {
	*kClient
}

func (p *kResourceUsageAgentClient) ReportCPUTime(ctx context.Context, callOptions ...callopt.Option) (stream ResourceUsageAgent_ReportCPUTimeClient, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ReportCPUTime(ctx)
}

func (p *kResourceUsageAgentClient) Report(ctx context.Context, callOptions ...callopt.Option) (stream ResourceUsageAgent_ReportClient, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Report(ctx)
}
