// Code generated by Kitex v0.1.3. DO NOT EDIT.

package externalstorage

import (
	"context"
	"github.com/cloudwego/kitex/client"
	"github.com/cloudwego/kitex/client/callopt"
	"github.com/pingcap/kvproto/proto/kitex_gen/brpb"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Restore(ctx context.Context, Req *brpb.ExternalStorageRestoreRequest, callOptions ...callopt.Option) (r *brpb.ExternalStorageRestoreResponse, err error)
	Save(ctx context.Context, Req *brpb.ExternalStorageSaveRequest, callOptions ...callopt.Option) (r *brpb.ExternalStorageSaveResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kExternalStorageClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kExternalStorageClient struct {
	*kClient
}

func (p *kExternalStorageClient) Restore(ctx context.Context, Req *brpb.ExternalStorageRestoreRequest, callOptions ...callopt.Option) (r *brpb.ExternalStorageRestoreResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Restore(ctx, Req)
}

func (p *kExternalStorageClient) Save(ctx context.Context, Req *brpb.ExternalStorageSaveRequest, callOptions ...callopt.Option) (r *brpb.ExternalStorageSaveResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Save(ctx, Req)
}
