// Code generated by Kitex v0.1.3. DO NOT EDIT.

package diagnostics

import (
	"context"
	"github.com/cloudwego/kitex/client"
	"github.com/cloudwego/kitex/client/callopt"
	"github.com/cloudwego/kitex/pkg/streaming"
	"github.com/cloudwego/kitex/transport"
	"github.com/pingcap/kvproto/proto/kitex_gen/diagnosticspb"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	SearchLog(ctx context.Context, Req *diagnosticspb.SearchLogRequest, callOptions ...callopt.Option) (stream Diagnostics_search_logClient, err error)
	ServerInfo(ctx context.Context, Req *diagnosticspb.ServerInfoRequest, callOptions ...callopt.Option) (r *diagnosticspb.ServerInfoResponse, err error)
}

type Diagnostics_search_logClient interface {
	streaming.Stream
	Recv() (*diagnosticspb.SearchLogResponse, error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, client.WithTransportProtocol(transport.GRPC))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kDiagnosticsClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kDiagnosticsClient struct {
	*kClient
}

func (p *kDiagnosticsClient) SearchLog(ctx context.Context, Req *diagnosticspb.SearchLogRequest, callOptions ...callopt.Option) (stream Diagnostics_search_logClient, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SearchLog(ctx, Req)
}

func (p *kDiagnosticsClient) ServerInfo(ctx context.Context, Req *diagnosticspb.ServerInfoRequest, callOptions ...callopt.Option) (r *diagnosticspb.ServerInfoResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ServerInfo(ctx, Req)
}
