// Code generated by Kitex v0.1.3. DO NOT EDIT.

package changedata

import (
	"context"
	"github.com/cloudwego/kitex/client"
	"github.com/cloudwego/kitex/client/callopt"
	"github.com/cloudwego/kitex/pkg/streaming"
	"github.com/cloudwego/kitex/transport"
	"github.com/pingcap/kvproto/proto/kitex_gen/cdcpb"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	EventFeed(ctx context.Context, callOptions ...callopt.Option) (stream ChangeData_EventFeedClient, err error)
}

type ChangeData_EventFeedClient interface {
	streaming.Stream
	Send(*cdcpb.ChangeDataRequest) error
	Recv() (*cdcpb.ChangeDataEvent, error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, client.WithTransportProtocol(transport.GRPC))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kChangeDataClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kChangeDataClient struct {
	*kClient
}

func (p *kChangeDataClient) EventFeed(ctx context.Context, callOptions ...callopt.Option) (stream ChangeData_EventFeedClient, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.EventFeed(ctx)
}
