// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.8.0
// source: import_kvpb.proto

package import_kvpb

import (
	context "context"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	_ "github.com/pingcap/kvproto/proto/kitex_gen/github.com/gogo/protobuf/gogoproto"
	import_sstpb "github.com/pingcap/kvproto/proto/kitex_gen/import_sstpb"
	_ "github.com/pingcap/kvproto/proto/kitex_gen/rustproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Mutation_OP int32

const (
	Mutation_Put Mutation_OP = 0
)

// Enum value maps for Mutation_OP.
var (
	Mutation_OP_name = map[int32]string{
		0: "Put",
	}
	Mutation_OP_value = map[string]int32{
		"Put": 0,
	}
)

func (x Mutation_OP) Enum() *Mutation_OP {
	p := new(Mutation_OP)
	*p = x
	return p
}

func (x Mutation_OP) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Mutation_OP) Descriptor() protoreflect.EnumDescriptor {
	return file_import_kvpb_proto_enumTypes[0].Descriptor()
}

func (Mutation_OP) Type() protoreflect.EnumType {
	return &file_import_kvpb_proto_enumTypes[0]
}

func (x Mutation_OP) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Mutation_OP.Descriptor instead.
func (Mutation_OP) EnumDescriptor() ([]byte, []int) {
	return file_import_kvpb_proto_rawDescGZIP(), []int{5, 0}
}

type SwitchModeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PdAddr  string                          `protobuf:"bytes,1,opt,name=pd_addr,json=pdAddr,proto3" json:"pd_addr,omitempty"`
	Request *import_sstpb.SwitchModeRequest `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
}

func (x *SwitchModeRequest) Reset() {
	*x = SwitchModeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_import_kvpb_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SwitchModeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchModeRequest) ProtoMessage() {}

func (x *SwitchModeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_import_kvpb_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchModeRequest.ProtoReflect.Descriptor instead.
func (*SwitchModeRequest) Descriptor() ([]byte, []int) {
	return file_import_kvpb_proto_rawDescGZIP(), []int{0}
}

func (x *SwitchModeRequest) GetPdAddr() string {
	if x != nil {
		return x.PdAddr
	}
	return ""
}

func (x *SwitchModeRequest) GetRequest() *import_sstpb.SwitchModeRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type SwitchModeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SwitchModeResponse) Reset() {
	*x = SwitchModeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_import_kvpb_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SwitchModeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchModeResponse) ProtoMessage() {}

func (x *SwitchModeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_import_kvpb_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchModeResponse.ProtoReflect.Descriptor instead.
func (*SwitchModeResponse) Descriptor() ([]byte, []int) {
	return file_import_kvpb_proto_rawDescGZIP(), []int{1}
}

type OpenEngineRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid      []byte `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	KeyPrefix []byte `protobuf:"bytes,2,opt,name=key_prefix,json=keyPrefix,proto3" json:"key_prefix,omitempty"`
}

func (x *OpenEngineRequest) Reset() {
	*x = OpenEngineRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_import_kvpb_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenEngineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenEngineRequest) ProtoMessage() {}

func (x *OpenEngineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_import_kvpb_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenEngineRequest.ProtoReflect.Descriptor instead.
func (*OpenEngineRequest) Descriptor() ([]byte, []int) {
	return file_import_kvpb_proto_rawDescGZIP(), []int{2}
}

func (x *OpenEngineRequest) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *OpenEngineRequest) GetKeyPrefix() []byte {
	if x != nil {
		return x.KeyPrefix
	}
	return nil
}

type OpenEngineResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OpenEngineResponse) Reset() {
	*x = OpenEngineResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_import_kvpb_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpenEngineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenEngineResponse) ProtoMessage() {}

func (x *OpenEngineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_import_kvpb_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenEngineResponse.ProtoReflect.Descriptor instead.
func (*OpenEngineResponse) Descriptor() ([]byte, []int) {
	return file_import_kvpb_proto_rawDescGZIP(), []int{3}
}

type WriteHead struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid []byte `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *WriteHead) Reset() {
	*x = WriteHead{}
	if protoimpl.UnsafeEnabled {
		mi := &file_import_kvpb_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteHead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteHead) ProtoMessage() {}

func (x *WriteHead) ProtoReflect() protoreflect.Message {
	mi := &file_import_kvpb_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteHead.ProtoReflect.Descriptor instead.
func (*WriteHead) Descriptor() ([]byte, []int) {
	return file_import_kvpb_proto_rawDescGZIP(), []int{4}
}

func (x *WriteHead) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

type Mutation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Op    Mutation_OP `protobuf:"varint,1,opt,name=op,proto3,enum=import_kvpb.Mutation_OP" json:"op,omitempty"`
	Key   []byte      `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte      `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Mutation) Reset() {
	*x = Mutation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_import_kvpb_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mutation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mutation) ProtoMessage() {}

func (x *Mutation) ProtoReflect() protoreflect.Message {
	mi := &file_import_kvpb_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mutation.ProtoReflect.Descriptor instead.
func (*Mutation) Descriptor() ([]byte, []int) {
	return file_import_kvpb_proto_rawDescGZIP(), []int{5}
}

func (x *Mutation) GetOp() Mutation_OP {
	if x != nil {
		return x.Op
	}
	return Mutation_Put
}

func (x *Mutation) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Mutation) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type WriteBatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CommitTs  uint64      `protobuf:"varint,1,opt,name=commit_ts,json=commitTs,proto3" json:"commit_ts,omitempty"`
	Mutations []*Mutation `protobuf:"bytes,2,rep,name=mutations,proto3" json:"mutations,omitempty"`
}

func (x *WriteBatch) Reset() {
	*x = WriteBatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_import_kvpb_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteBatch) ProtoMessage() {}

func (x *WriteBatch) ProtoReflect() protoreflect.Message {
	mi := &file_import_kvpb_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteBatch.ProtoReflect.Descriptor instead.
func (*WriteBatch) Descriptor() ([]byte, []int) {
	return file_import_kvpb_proto_rawDescGZIP(), []int{6}
}

func (x *WriteBatch) GetCommitTs() uint64 {
	if x != nil {
		return x.CommitTs
	}
	return 0
}

func (x *WriteBatch) GetMutations() []*Mutation {
	if x != nil {
		return x.Mutations
	}
	return nil
}

type WriteEngineRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Chunk:
	//	*WriteEngineRequest_Head
	//	*WriteEngineRequest_Batch
	Chunk isWriteEngineRequest_Chunk `protobuf_oneof:"chunk"`
}

func (x *WriteEngineRequest) Reset() {
	*x = WriteEngineRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_import_kvpb_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteEngineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteEngineRequest) ProtoMessage() {}

func (x *WriteEngineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_import_kvpb_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteEngineRequest.ProtoReflect.Descriptor instead.
func (*WriteEngineRequest) Descriptor() ([]byte, []int) {
	return file_import_kvpb_proto_rawDescGZIP(), []int{7}
}

func (m *WriteEngineRequest) GetChunk() isWriteEngineRequest_Chunk {
	if m != nil {
		return m.Chunk
	}
	return nil
}

func (x *WriteEngineRequest) GetHead() *WriteHead {
	if x, ok := x.GetChunk().(*WriteEngineRequest_Head); ok {
		return x.Head
	}
	return nil
}

func (x *WriteEngineRequest) GetBatch() *WriteBatch {
	if x, ok := x.GetChunk().(*WriteEngineRequest_Batch); ok {
		return x.Batch
	}
	return nil
}

type isWriteEngineRequest_Chunk interface {
	isWriteEngineRequest_Chunk()
}

type WriteEngineRequest_Head struct {
	Head *WriteHead `protobuf:"bytes,1,opt,name=head,proto3,oneof"`
}

type WriteEngineRequest_Batch struct {
	Batch *WriteBatch `protobuf:"bytes,2,opt,name=batch,proto3,oneof"`
}

func (*WriteEngineRequest_Head) isWriteEngineRequest_Chunk() {}

func (*WriteEngineRequest_Batch) isWriteEngineRequest_Chunk() {}

type KVPair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *KVPair) Reset() {
	*x = KVPair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_import_kvpb_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KVPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVPair) ProtoMessage() {}

func (x *KVPair) ProtoReflect() protoreflect.Message {
	mi := &file_import_kvpb_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVPair.ProtoReflect.Descriptor instead.
func (*KVPair) Descriptor() ([]byte, []int) {
	return file_import_kvpb_proto_rawDescGZIP(), []int{8}
}

func (x *KVPair) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *KVPair) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type WriteEngineV3Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid     []byte    `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	CommitTs uint64    `protobuf:"varint,2,opt,name=commit_ts,json=commitTs,proto3" json:"commit_ts,omitempty"`
	Pairs    []*KVPair `protobuf:"bytes,3,rep,name=pairs,proto3" json:"pairs,omitempty"`
}

func (x *WriteEngineV3Request) Reset() {
	*x = WriteEngineV3Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_import_kvpb_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteEngineV3Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteEngineV3Request) ProtoMessage() {}

func (x *WriteEngineV3Request) ProtoReflect() protoreflect.Message {
	mi := &file_import_kvpb_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteEngineV3Request.ProtoReflect.Descriptor instead.
func (*WriteEngineV3Request) Descriptor() ([]byte, []int) {
	return file_import_kvpb_proto_rawDescGZIP(), []int{9}
}

func (x *WriteEngineV3Request) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *WriteEngineV3Request) GetCommitTs() uint64 {
	if x != nil {
		return x.CommitTs
	}
	return 0
}

func (x *WriteEngineV3Request) GetPairs() []*KVPair {
	if x != nil {
		return x.Pairs
	}
	return nil
}

type WriteEngineResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *Error `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *WriteEngineResponse) Reset() {
	*x = WriteEngineResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_import_kvpb_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WriteEngineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteEngineResponse) ProtoMessage() {}

func (x *WriteEngineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_import_kvpb_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteEngineResponse.ProtoReflect.Descriptor instead.
func (*WriteEngineResponse) Descriptor() ([]byte, []int) {
	return file_import_kvpb_proto_rawDescGZIP(), []int{10}
}

func (x *WriteEngineResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type CloseEngineRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid []byte `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *CloseEngineRequest) Reset() {
	*x = CloseEngineRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_import_kvpb_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloseEngineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseEngineRequest) ProtoMessage() {}

func (x *CloseEngineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_import_kvpb_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseEngineRequest.ProtoReflect.Descriptor instead.
func (*CloseEngineRequest) Descriptor() ([]byte, []int) {
	return file_import_kvpb_proto_rawDescGZIP(), []int{11}
}

func (x *CloseEngineRequest) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

type CloseEngineResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error *Error `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *CloseEngineResponse) Reset() {
	*x = CloseEngineResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_import_kvpb_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CloseEngineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseEngineResponse) ProtoMessage() {}

func (x *CloseEngineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_import_kvpb_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseEngineResponse.ProtoReflect.Descriptor instead.
func (*CloseEngineResponse) Descriptor() ([]byte, []int) {
	return file_import_kvpb_proto_rawDescGZIP(), []int{12}
}

func (x *CloseEngineResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type ImportEngineRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid   []byte `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	PdAddr string `protobuf:"bytes,2,opt,name=pd_addr,json=pdAddr,proto3" json:"pd_addr,omitempty"`
}

func (x *ImportEngineRequest) Reset() {
	*x = ImportEngineRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_import_kvpb_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImportEngineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportEngineRequest) ProtoMessage() {}

func (x *ImportEngineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_import_kvpb_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportEngineRequest.ProtoReflect.Descriptor instead.
func (*ImportEngineRequest) Descriptor() ([]byte, []int) {
	return file_import_kvpb_proto_rawDescGZIP(), []int{13}
}

func (x *ImportEngineRequest) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

func (x *ImportEngineRequest) GetPdAddr() string {
	if x != nil {
		return x.PdAddr
	}
	return ""
}

type ImportEngineResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ImportEngineResponse) Reset() {
	*x = ImportEngineResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_import_kvpb_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImportEngineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportEngineResponse) ProtoMessage() {}

func (x *ImportEngineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_import_kvpb_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportEngineResponse.ProtoReflect.Descriptor instead.
func (*ImportEngineResponse) Descriptor() ([]byte, []int) {
	return file_import_kvpb_proto_rawDescGZIP(), []int{14}
}

type CleanupEngineRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid []byte `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *CleanupEngineRequest) Reset() {
	*x = CleanupEngineRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_import_kvpb_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CleanupEngineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanupEngineRequest) ProtoMessage() {}

func (x *CleanupEngineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_import_kvpb_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanupEngineRequest.ProtoReflect.Descriptor instead.
func (*CleanupEngineRequest) Descriptor() ([]byte, []int) {
	return file_import_kvpb_proto_rawDescGZIP(), []int{15}
}

func (x *CleanupEngineRequest) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

type CleanupEngineResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CleanupEngineResponse) Reset() {
	*x = CleanupEngineResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_import_kvpb_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CleanupEngineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanupEngineResponse) ProtoMessage() {}

func (x *CleanupEngineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_import_kvpb_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanupEngineResponse.ProtoReflect.Descriptor instead.
func (*CleanupEngineResponse) Descriptor() ([]byte, []int) {
	return file_import_kvpb_proto_rawDescGZIP(), []int{16}
}

type CompactClusterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PdAddr  string                       `protobuf:"bytes,1,opt,name=pd_addr,json=pdAddr,proto3" json:"pd_addr,omitempty"`
	Request *import_sstpb.CompactRequest `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
}

func (x *CompactClusterRequest) Reset() {
	*x = CompactClusterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_import_kvpb_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompactClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactClusterRequest) ProtoMessage() {}

func (x *CompactClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_import_kvpb_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactClusterRequest.ProtoReflect.Descriptor instead.
func (*CompactClusterRequest) Descriptor() ([]byte, []int) {
	return file_import_kvpb_proto_rawDescGZIP(), []int{17}
}

func (x *CompactClusterRequest) GetPdAddr() string {
	if x != nil {
		return x.PdAddr
	}
	return ""
}

func (x *CompactClusterRequest) GetRequest() *import_sstpb.CompactRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type CompactClusterResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CompactClusterResponse) Reset() {
	*x = CompactClusterResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_import_kvpb_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompactClusterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactClusterResponse) ProtoMessage() {}

func (x *CompactClusterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_import_kvpb_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactClusterResponse.ProtoReflect.Descriptor instead.
func (*CompactClusterResponse) Descriptor() ([]byte, []int) {
	return file_import_kvpb_proto_rawDescGZIP(), []int{18}
}

type GetVersionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetVersionRequest) Reset() {
	*x = GetVersionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_import_kvpb_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionRequest) ProtoMessage() {}

func (x *GetVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_import_kvpb_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionRequest.ProtoReflect.Descriptor instead.
func (*GetVersionRequest) Descriptor() ([]byte, []int) {
	return file_import_kvpb_proto_rawDescGZIP(), []int{19}
}

type GetVersionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Commit  string `protobuf:"bytes,2,opt,name=commit,proto3" json:"commit,omitempty"`
}

func (x *GetVersionResponse) Reset() {
	*x = GetVersionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_import_kvpb_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionResponse) ProtoMessage() {}

func (x *GetVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_import_kvpb_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionResponse.ProtoReflect.Descriptor instead.
func (*GetVersionResponse) Descriptor() ([]byte, []int) {
	return file_import_kvpb_proto_rawDescGZIP(), []int{20}
}

func (x *GetVersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetVersionResponse) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

type GetMetricsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetMetricsRequest) Reset() {
	*x = GetMetricsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_import_kvpb_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsRequest) ProtoMessage() {}

func (x *GetMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_import_kvpb_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetMetricsRequest) Descriptor() ([]byte, []int) {
	return file_import_kvpb_proto_rawDescGZIP(), []int{21}
}

type GetMetricsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prometheus string `protobuf:"bytes,1,opt,name=prometheus,proto3" json:"prometheus,omitempty"`
}

func (x *GetMetricsResponse) Reset() {
	*x = GetMetricsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_import_kvpb_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsResponse) ProtoMessage() {}

func (x *GetMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_import_kvpb_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetMetricsResponse) Descriptor() ([]byte, []int) {
	return file_import_kvpb_proto_rawDescGZIP(), []int{22}
}

func (x *GetMetricsResponse) GetPrometheus() string {
	if x != nil {
		return x.Prometheus
	}
	return ""
}

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// This can happen if the client hasn't opened the engine, or the server
	// restarts while the client is writing or closing. An unclosed engine will
	// be removed on server restart, so the client should not continue but
	// restart the previous job in that case.
	EngineNotFound *Error_EngineNotFound `protobuf:"bytes,1,opt,name=engine_not_found,json=engineNotFound,proto3" json:"engine_not_found,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_import_kvpb_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_import_kvpb_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_import_kvpb_proto_rawDescGZIP(), []int{23}
}

func (x *Error) GetEngineNotFound() *Error_EngineNotFound {
	if x != nil {
		return x.EngineNotFound
	}
	return nil
}

type Error_EngineNotFound struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid []byte `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *Error_EngineNotFound) Reset() {
	*x = Error_EngineNotFound{}
	if protoimpl.UnsafeEnabled {
		mi := &file_import_kvpb_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error_EngineNotFound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error_EngineNotFound) ProtoMessage() {}

func (x *Error_EngineNotFound) ProtoReflect() protoreflect.Message {
	mi := &file_import_kvpb_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error_EngineNotFound.ProtoReflect.Descriptor instead.
func (*Error_EngineNotFound) Descriptor() ([]byte, []int) {
	return file_import_kvpb_proto_rawDescGZIP(), []int{23, 0}
}

func (x *Error_EngineNotFound) GetUuid() []byte {
	if x != nil {
		return x.Uuid
	}
	return nil
}

var File_import_kvpb_proto protoreflect.FileDescriptor

var file_import_kvpb_proto_rawDesc = []byte{
	0x0a, 0x11, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x6b, 0x76, 0x70, 0x62, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x6b, 0x76, 0x70, 0x62,
	0x1a, 0x12, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x73, 0x73, 0x74, 0x70, 0x62, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x67, 0x6f, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x67, 0x6f, 0x67, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0f, 0x72, 0x75, 0x73, 0x74,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x67, 0x0a, 0x11, 0x53,
	0x77, 0x69, 0x74, 0x63, 0x68, 0x4d, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x70, 0x64, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x70, 0x64, 0x41, 0x64, 0x64, 0x72, 0x12, 0x39, 0x0a, 0x07, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x69, 0x6d, 0x70,
	0x6f, 0x72, 0x74, 0x5f, 0x73, 0x73, 0x74, 0x70, 0x62, 0x2e, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68,
	0x4d, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x07, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x22, 0x14, 0x0a, 0x12, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x4d, 0x6f,
	0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x46, 0x0a, 0x11, 0x4f, 0x70,
	0x65, 0x6e, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x75,
	0x75, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x6b, 0x65, 0x79, 0x5f, 0x70, 0x72, 0x65, 0x66, 0x69,
	0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x6b, 0x65, 0x79, 0x50, 0x72, 0x65, 0x66,
	0x69, 0x78, 0x22, 0x14, 0x0a, 0x12, 0x4f, 0x70, 0x65, 0x6e, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1f, 0x0a, 0x09, 0x57, 0x72, 0x69, 0x74,
	0x65, 0x48, 0x65, 0x61, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x6b, 0x0a, 0x08, 0x4d, 0x75, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x28, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x18, 0x2e, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x6b, 0x76, 0x70, 0x62, 0x2e,
	0x4d, 0x75, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4f, 0x50, 0x52, 0x02, 0x6f, 0x70, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x0d, 0x0a, 0x02, 0x4f, 0x50, 0x12, 0x07, 0x0a,
	0x03, 0x50, 0x75, 0x74, 0x10, 0x00, 0x22, 0x5e, 0x0a, 0x0a, 0x57, 0x72, 0x69, 0x74, 0x65, 0x42,
	0x61, 0x74, 0x63, 0x68, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x5f, 0x74,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x54,
	0x73, 0x12, 0x33, 0x0a, 0x09, 0x6d, 0x75, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x6b, 0x76,
	0x70, 0x62, 0x2e, 0x4d, 0x75, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x6d, 0x75, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x7c, 0x0a, 0x12, 0x57, 0x72, 0x69, 0x74, 0x65, 0x45,
	0x6e, 0x67, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x04,
	0x68, 0x65, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x69, 0x6d, 0x70,
	0x6f, 0x72, 0x74, 0x5f, 0x6b, 0x76, 0x70, 0x62, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x48, 0x65,
	0x61, 0x64, 0x48, 0x00, 0x52, 0x04, 0x68, 0x65, 0x61, 0x64, 0x12, 0x2f, 0x0a, 0x05, 0x62, 0x61,
	0x74, 0x63, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x69, 0x6d, 0x70, 0x6f,
	0x72, 0x74, 0x5f, 0x6b, 0x76, 0x70, 0x62, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x42, 0x61, 0x74,
	0x63, 0x68, 0x48, 0x00, 0x52, 0x05, 0x62, 0x61, 0x74, 0x63, 0x68, 0x42, 0x07, 0x0a, 0x05, 0x63,
	0x68, 0x75, 0x6e, 0x6b, 0x22, 0x30, 0x0a, 0x06, 0x4b, 0x56, 0x50, 0x61, 0x69, 0x72, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x72, 0x0a, 0x14, 0x57, 0x72, 0x69, 0x74, 0x65, 0x45,
	0x6e, 0x67, 0x69, 0x6e, 0x65, 0x56, 0x33, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x75, 0x75,
	0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x5f, 0x74, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x54, 0x73, 0x12,
	0x29, 0x0a, 0x05, 0x70, 0x61, 0x69, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x6b, 0x76, 0x70, 0x62, 0x2e, 0x4b, 0x56, 0x50,
	0x61, 0x69, 0x72, 0x52, 0x05, 0x70, 0x61, 0x69, 0x72, 0x73, 0x22, 0x3f, 0x0a, 0x13, 0x57, 0x72,
	0x69, 0x74, 0x65, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x28, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x6b, 0x76, 0x70, 0x62, 0x2e, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x28, 0x0a, 0x12, 0x43,
	0x6c, 0x6f, 0x73, 0x65, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x3f, 0x0a, 0x13, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x45, 0x6e,
	0x67, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x69, 0x6d,
	0x70, 0x6f, 0x72, 0x74, 0x5f, 0x6b, 0x76, 0x70, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x42, 0x0a, 0x13, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74,
	0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x75, 0x75, 0x69,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x64, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x70, 0x64, 0x41, 0x64, 0x64, 0x72, 0x22, 0x16, 0x0a, 0x14, 0x49, 0x6d,
	0x70, 0x6f, 0x72, 0x74, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x2a, 0x0a, 0x14, 0x43, 0x6c, 0x65, 0x61, 0x6e, 0x75, 0x70, 0x45, 0x6e, 0x67,
	0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x17,
	0x0a, 0x15, 0x43, 0x6c, 0x65, 0x61, 0x6e, 0x75, 0x70, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x68, 0x0a, 0x15, 0x43, 0x6f, 0x6d, 0x70, 0x61,
	0x63, 0x74, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x70, 0x64, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x70, 0x64, 0x41, 0x64, 0x64, 0x72, 0x12, 0x36, 0x0a, 0x07, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x69, 0x6d, 0x70,
	0x6f, 0x72, 0x74, 0x5f, 0x73, 0x73, 0x74, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x63,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x18, 0x0a, 0x16, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x63, 0x74, 0x43, 0x6c, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x13, 0x0a, 0x11, 0x47,
	0x65, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x46, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x22, 0x13, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4d,
	0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x34, 0x0a,
	0x12, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x6d, 0x65, 0x74, 0x68, 0x65, 0x75,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x6d, 0x65, 0x74, 0x68,
	0x65, 0x75, 0x73, 0x22, 0x7a, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x4b, 0x0a, 0x10,
	0x65, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x5f, 0x6e, 0x6f, 0x74, 0x5f, 0x66, 0x6f, 0x75, 0x6e, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x5f,
	0x6b, 0x76, 0x70, 0x62, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x45, 0x6e, 0x67, 0x69, 0x6e,
	0x65, 0x4e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x52, 0x0e, 0x65, 0x6e, 0x67, 0x69, 0x6e,
	0x65, 0x4e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x1a, 0x24, 0x0a, 0x0e, 0x45, 0x6e, 0x67,
	0x69, 0x6e, 0x65, 0x4e, 0x6f, 0x74, 0x46, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x75,
	0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x32,
	0xde, 0x06, 0x0a, 0x08, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x4b, 0x56, 0x12, 0x4f, 0x0a, 0x0a,
	0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x1e, 0x2e, 0x69, 0x6d, 0x70,
	0x6f, 0x72, 0x74, 0x5f, 0x6b, 0x76, 0x70, 0x62, 0x2e, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x4d,
	0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x69, 0x6d, 0x70,
	0x6f, 0x72, 0x74, 0x5f, 0x6b, 0x76, 0x70, 0x62, 0x2e, 0x53, 0x77, 0x69, 0x74, 0x63, 0x68, 0x4d,
	0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4f, 0x0a,
	0x0a, 0x4f, 0x70, 0x65, 0x6e, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x12, 0x1e, 0x2e, 0x69, 0x6d,
	0x70, 0x6f, 0x72, 0x74, 0x5f, 0x6b, 0x76, 0x70, 0x62, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x45, 0x6e,
	0x67, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x69, 0x6d,
	0x70, 0x6f, 0x72, 0x74, 0x5f, 0x6b, 0x76, 0x70, 0x62, 0x2e, 0x4f, 0x70, 0x65, 0x6e, 0x45, 0x6e,
	0x67, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x54,
	0x0a, 0x0b, 0x57, 0x72, 0x69, 0x74, 0x65, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x12, 0x1f, 0x2e,
	0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x6b, 0x76, 0x70, 0x62, 0x2e, 0x57, 0x72, 0x69, 0x74,
	0x65, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20,
	0x2e, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x6b, 0x76, 0x70, 0x62, 0x2e, 0x57, 0x72, 0x69,
	0x74, 0x65, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x28, 0x01, 0x12, 0x56, 0x0a, 0x0d, 0x57, 0x72, 0x69, 0x74, 0x65, 0x45, 0x6e, 0x67,
	0x69, 0x6e, 0x65, 0x56, 0x33, 0x12, 0x21, 0x2e, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x6b,
	0x76, 0x70, 0x62, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x56,
	0x33, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x69, 0x6d, 0x70, 0x6f, 0x72,
	0x74, 0x5f, 0x6b, 0x76, 0x70, 0x62, 0x2e, 0x57, 0x72, 0x69, 0x74, 0x65, 0x45, 0x6e, 0x67, 0x69,
	0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x0b,
	0x43, 0x6c, 0x6f, 0x73, 0x65, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x12, 0x1f, 0x2e, 0x69, 0x6d,
	0x70, 0x6f, 0x72, 0x74, 0x5f, 0x6b, 0x76, 0x70, 0x62, 0x2e, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x45,
	0x6e, 0x67, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x69,
	0x6d, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x6b, 0x76, 0x70, 0x62, 0x2e, 0x43, 0x6c, 0x6f, 0x73, 0x65,
	0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x55, 0x0a, 0x0c, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65,
	0x12, 0x20, 0x2e, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x6b, 0x76, 0x70, 0x62, 0x2e, 0x49,
	0x6d, 0x70, 0x6f, 0x72, 0x74, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x21, 0x2e, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x6b, 0x76, 0x70, 0x62,
	0x2e, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x58, 0x0a, 0x0d, 0x43, 0x6c, 0x65, 0x61, 0x6e,
	0x75, 0x70, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x12, 0x21, 0x2e, 0x69, 0x6d, 0x70, 0x6f, 0x72,
	0x74, 0x5f, 0x6b, 0x76, 0x70, 0x62, 0x2e, 0x43, 0x6c, 0x65, 0x61, 0x6e, 0x75, 0x70, 0x45, 0x6e,
	0x67, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x69, 0x6d,
	0x70, 0x6f, 0x72, 0x74, 0x5f, 0x6b, 0x76, 0x70, 0x62, 0x2e, 0x43, 0x6c, 0x65, 0x61, 0x6e, 0x75,
	0x70, 0x45, 0x6e, 0x67, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x5b, 0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x63, 0x74, 0x43, 0x6c, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x12, 0x22, 0x2e, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x6b, 0x76, 0x70,
	0x62, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x63, 0x74, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74,
	0x5f, 0x6b, 0x76, 0x70, 0x62, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x63, 0x74, 0x43, 0x6c, 0x75,
	0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4f,
	0x0a, 0x0a, 0x47, 0x65, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x2e, 0x69,
	0x6d, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x6b, 0x76, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x69,
	0x6d, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x6b, 0x76, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x4f, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x12, 0x1e, 0x2e,
	0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x6b, 0x76, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x4d,
	0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e,
	0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x6b, 0x76, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x4d,
	0x65, 0x74, 0x72, 0x69, 0x63, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x5a, 0x0a, 0x10, 0x6f, 0x72, 0x67, 0x2e, 0x74, 0x69, 0x6b, 0x76, 0x2e, 0x6b, 0x76, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x5a, 0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x70, 0x69, 0x6e, 0x67, 0x63, 0x61, 0x70, 0x2f, 0x6b, 0x76, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6b, 0x69, 0x74, 0x65, 0x78, 0x5f, 0x67, 0x65, 0x6e,
	0x2f, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x6b, 0x76, 0x70, 0x62, 0xe0, 0xe2, 0x1e, 0x01,
	0xc8, 0xe2, 0x1e, 0x01, 0xd0, 0xe2, 0x1e, 0x01, 0xd8, 0xa8, 0x08, 0x01, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_import_kvpb_proto_rawDescOnce sync.Once
	file_import_kvpb_proto_rawDescData = file_import_kvpb_proto_rawDesc
)

func file_import_kvpb_proto_rawDescGZIP() []byte {
	file_import_kvpb_proto_rawDescOnce.Do(func() {
		file_import_kvpb_proto_rawDescData = protoimpl.X.CompressGZIP(file_import_kvpb_proto_rawDescData)
	})
	return file_import_kvpb_proto_rawDescData
}

var file_import_kvpb_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_import_kvpb_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_import_kvpb_proto_goTypes = []interface{}{
	(Mutation_OP)(0),                       // 0: import_kvpb.Mutation.OP
	(*SwitchModeRequest)(nil),              // 1: import_kvpb.SwitchModeRequest
	(*SwitchModeResponse)(nil),             // 2: import_kvpb.SwitchModeResponse
	(*OpenEngineRequest)(nil),              // 3: import_kvpb.OpenEngineRequest
	(*OpenEngineResponse)(nil),             // 4: import_kvpb.OpenEngineResponse
	(*WriteHead)(nil),                      // 5: import_kvpb.WriteHead
	(*Mutation)(nil),                       // 6: import_kvpb.Mutation
	(*WriteBatch)(nil),                     // 7: import_kvpb.WriteBatch
	(*WriteEngineRequest)(nil),             // 8: import_kvpb.WriteEngineRequest
	(*KVPair)(nil),                         // 9: import_kvpb.KVPair
	(*WriteEngineV3Request)(nil),           // 10: import_kvpb.WriteEngineV3Request
	(*WriteEngineResponse)(nil),            // 11: import_kvpb.WriteEngineResponse
	(*CloseEngineRequest)(nil),             // 12: import_kvpb.CloseEngineRequest
	(*CloseEngineResponse)(nil),            // 13: import_kvpb.CloseEngineResponse
	(*ImportEngineRequest)(nil),            // 14: import_kvpb.ImportEngineRequest
	(*ImportEngineResponse)(nil),           // 15: import_kvpb.ImportEngineResponse
	(*CleanupEngineRequest)(nil),           // 16: import_kvpb.CleanupEngineRequest
	(*CleanupEngineResponse)(nil),          // 17: import_kvpb.CleanupEngineResponse
	(*CompactClusterRequest)(nil),          // 18: import_kvpb.CompactClusterRequest
	(*CompactClusterResponse)(nil),         // 19: import_kvpb.CompactClusterResponse
	(*GetVersionRequest)(nil),              // 20: import_kvpb.GetVersionRequest
	(*GetVersionResponse)(nil),             // 21: import_kvpb.GetVersionResponse
	(*GetMetricsRequest)(nil),              // 22: import_kvpb.GetMetricsRequest
	(*GetMetricsResponse)(nil),             // 23: import_kvpb.GetMetricsResponse
	(*Error)(nil),                          // 24: import_kvpb.Error
	(*Error_EngineNotFound)(nil),           // 25: import_kvpb.Error.EngineNotFound
	(*import_sstpb.SwitchModeRequest)(nil), // 26: import_sstpb.SwitchModeRequest
	(*import_sstpb.CompactRequest)(nil),    // 27: import_sstpb.CompactRequest
}
var file_import_kvpb_proto_depIdxs = []int32{
	26, // 0: import_kvpb.SwitchModeRequest.request:type_name -> import_sstpb.SwitchModeRequest
	0,  // 1: import_kvpb.Mutation.op:type_name -> import_kvpb.Mutation.OP
	6,  // 2: import_kvpb.WriteBatch.mutations:type_name -> import_kvpb.Mutation
	5,  // 3: import_kvpb.WriteEngineRequest.head:type_name -> import_kvpb.WriteHead
	7,  // 4: import_kvpb.WriteEngineRequest.batch:type_name -> import_kvpb.WriteBatch
	9,  // 5: import_kvpb.WriteEngineV3Request.pairs:type_name -> import_kvpb.KVPair
	24, // 6: import_kvpb.WriteEngineResponse.error:type_name -> import_kvpb.Error
	24, // 7: import_kvpb.CloseEngineResponse.error:type_name -> import_kvpb.Error
	27, // 8: import_kvpb.CompactClusterRequest.request:type_name -> import_sstpb.CompactRequest
	25, // 9: import_kvpb.Error.engine_not_found:type_name -> import_kvpb.Error.EngineNotFound
	1,  // 10: import_kvpb.ImportKV.SwitchMode:input_type -> import_kvpb.SwitchModeRequest
	3,  // 11: import_kvpb.ImportKV.OpenEngine:input_type -> import_kvpb.OpenEngineRequest
	8,  // 12: import_kvpb.ImportKV.WriteEngine:input_type -> import_kvpb.WriteEngineRequest
	10, // 13: import_kvpb.ImportKV.WriteEngineV3:input_type -> import_kvpb.WriteEngineV3Request
	12, // 14: import_kvpb.ImportKV.CloseEngine:input_type -> import_kvpb.CloseEngineRequest
	14, // 15: import_kvpb.ImportKV.ImportEngine:input_type -> import_kvpb.ImportEngineRequest
	16, // 16: import_kvpb.ImportKV.CleanupEngine:input_type -> import_kvpb.CleanupEngineRequest
	18, // 17: import_kvpb.ImportKV.CompactCluster:input_type -> import_kvpb.CompactClusterRequest
	20, // 18: import_kvpb.ImportKV.GetVersion:input_type -> import_kvpb.GetVersionRequest
	22, // 19: import_kvpb.ImportKV.GetMetrics:input_type -> import_kvpb.GetMetricsRequest
	2,  // 20: import_kvpb.ImportKV.SwitchMode:output_type -> import_kvpb.SwitchModeResponse
	4,  // 21: import_kvpb.ImportKV.OpenEngine:output_type -> import_kvpb.OpenEngineResponse
	11, // 22: import_kvpb.ImportKV.WriteEngine:output_type -> import_kvpb.WriteEngineResponse
	11, // 23: import_kvpb.ImportKV.WriteEngineV3:output_type -> import_kvpb.WriteEngineResponse
	13, // 24: import_kvpb.ImportKV.CloseEngine:output_type -> import_kvpb.CloseEngineResponse
	15, // 25: import_kvpb.ImportKV.ImportEngine:output_type -> import_kvpb.ImportEngineResponse
	17, // 26: import_kvpb.ImportKV.CleanupEngine:output_type -> import_kvpb.CleanupEngineResponse
	19, // 27: import_kvpb.ImportKV.CompactCluster:output_type -> import_kvpb.CompactClusterResponse
	21, // 28: import_kvpb.ImportKV.GetVersion:output_type -> import_kvpb.GetVersionResponse
	23, // 29: import_kvpb.ImportKV.GetMetrics:output_type -> import_kvpb.GetMetricsResponse
	20, // [20:30] is the sub-list for method output_type
	10, // [10:20] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_import_kvpb_proto_init() }
func file_import_kvpb_proto_init() {
	if File_import_kvpb_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_import_kvpb_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SwitchModeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_import_kvpb_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SwitchModeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_import_kvpb_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenEngineRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_import_kvpb_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpenEngineResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_import_kvpb_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteHead); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_import_kvpb_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mutation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_import_kvpb_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteBatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_import_kvpb_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteEngineRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_import_kvpb_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KVPair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_import_kvpb_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteEngineV3Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_import_kvpb_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WriteEngineResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_import_kvpb_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloseEngineRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_import_kvpb_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CloseEngineResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_import_kvpb_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImportEngineRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_import_kvpb_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImportEngineResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_import_kvpb_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CleanupEngineRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_import_kvpb_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CleanupEngineResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_import_kvpb_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompactClusterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_import_kvpb_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompactClusterResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_import_kvpb_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVersionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_import_kvpb_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetVersionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_import_kvpb_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMetricsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_import_kvpb_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMetricsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_import_kvpb_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_import_kvpb_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error_EngineNotFound); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_import_kvpb_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*WriteEngineRequest_Head)(nil),
		(*WriteEngineRequest_Batch)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_import_kvpb_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_import_kvpb_proto_goTypes,
		DependencyIndexes: file_import_kvpb_proto_depIdxs,
		EnumInfos:         file_import_kvpb_proto_enumTypes,
		MessageInfos:      file_import_kvpb_proto_msgTypes,
	}.Build()
	File_import_kvpb_proto = out.File
	file_import_kvpb_proto_rawDesc = nil
	file_import_kvpb_proto_goTypes = nil
	file_import_kvpb_proto_depIdxs = nil
}

var _ context.Context

// Code generated by Kitex v0.1.3. DO NOT EDIT.

type ImportKV interface {
	SwitchMode(ctx context.Context, req *SwitchModeRequest) (res *SwitchModeResponse, err error)
	OpenEngine(ctx context.Context, req *OpenEngineRequest) (res *OpenEngineResponse, err error)
	WriteEngine(stream ImportKV_WriteEngineServer) (err error)
	WriteEngineV3(ctx context.Context, req *WriteEngineV3Request) (res *WriteEngineResponse, err error)
	CloseEngine(ctx context.Context, req *CloseEngineRequest) (res *CloseEngineResponse, err error)
	ImportEngine(ctx context.Context, req *ImportEngineRequest) (res *ImportEngineResponse, err error)
	CleanupEngine(ctx context.Context, req *CleanupEngineRequest) (res *CleanupEngineResponse, err error)
	CompactCluster(ctx context.Context, req *CompactClusterRequest) (res *CompactClusterResponse, err error)
	GetVersion(ctx context.Context, req *GetVersionRequest) (res *GetVersionResponse, err error)
	GetMetrics(ctx context.Context, req *GetMetricsRequest) (res *GetMetricsResponse, err error)
}

type ImportKV_WriteEngineServer interface {
	streaming.Stream
	Recv() (*WriteEngineRequest, error)
	SendAndClose(*WriteEngineResponse) error
}
