// Code generated by Kitex v0.1.3. DO NOT EDIT.

package resourcemeteringpubsub

import (
	"context"
	"github.com/cloudwego/kitex/client"
	"github.com/cloudwego/kitex/client/callopt"
	"github.com/cloudwego/kitex/pkg/streaming"
	"github.com/cloudwego/kitex/transport"
	"github.com/pingcap/kvproto/proto/kitex_gen/resource_usage_agent"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Subscribe(ctx context.Context, Req *resource_usage_agent.ResourceMeteringRequest, callOptions ...callopt.Option) (stream ResourceMeteringPubSub_SubscribeClient, err error)
}

type ResourceMeteringPubSub_SubscribeClient interface {
	streaming.Stream
	Recv() (*resource_usage_agent.ResourceUsageRecord, error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, client.WithTransportProtocol(transport.GRPC))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kResourceMeteringPubSubClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kResourceMeteringPubSubClient struct {
	*kClient
}

func (p *kResourceMeteringPubSubClient) Subscribe(ctx context.Context, Req *resource_usage_agent.ResourceMeteringRequest, callOptions ...callopt.Option) (stream ResourceMeteringPubSub_SubscribeClient, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Subscribe(ctx, Req)
}
