// Code generated by Kitex v0.1.3. DO NOT EDIT.

package engine

import (
	"context"
	"github.com/cloudwego/kitex/client"
	"github.com/cloudwego/kitex/client/callopt"
	"github.com/cloudwego/kitex/pkg/streaming"
	"github.com/cloudwego/kitex/transport"
	"github.com/pingcap/kvproto/proto/kitex_gen/enginepb"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	ApplyCommandBatch(ctx context.Context, callOptions ...callopt.Option) (stream Engine_ApplyCommandBatchClient, err error)
	ApplySnapshot(ctx context.Context, callOptions ...callopt.Option) (stream Engine_ApplySnapshotClient, err error)
}

type Engine_ApplyCommandBatchClient interface {
	streaming.Stream
	Send(*enginepb.CommandRequestBatch) error
	Recv() (*enginepb.CommandResponseBatch, error)
}

type Engine_ApplySnapshotClient interface {
	streaming.Stream
	Send(*enginepb.SnapshotRequest) error
	CloseAndRecv() (*enginepb.SnapshotDone, error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, client.WithTransportProtocol(transport.GRPC))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kEngineClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kEngineClient struct {
	*kClient
}

func (p *kEngineClient) ApplyCommandBatch(ctx context.Context, callOptions ...callopt.Option) (stream Engine_ApplyCommandBatchClient, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ApplyCommandBatch(ctx)
}

func (p *kEngineClient) ApplySnapshot(ctx context.Context, callOptions ...callopt.Option) (stream Engine_ApplySnapshotClient, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ApplySnapshot(ctx)
}
