// Code generated by Kitex v0.1.2. DO NOT EDIT.

package deadlock

import (
	"context"
	"github.com/cloudwego/kitex/client"
	"github.com/cloudwego/kitex/client/callopt"
	"github.com/cloudwego/kitex/pkg/streaming"
	"github.com/cloudwego/kitex/transport"
	"github.com/pingcap/kvproto/proto/kitex_gen/deadlock"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetWaitForEntries(ctx context.Context, Req *deadlock.WaitForEntriesRequest, callOptions ...callopt.Option) (r *deadlock.WaitForEntriesResponse, err error)
	Detect(ctx context.Context, callOptions ...callopt.Option) (stream Deadlock_DetectClient, err error)
}

type Deadlock_DetectClient interface {
	streaming.Stream
	Send(*deadlock.DeadlockRequest) error
	Recv() (*deadlock.DeadlockResponse, error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, client.WithTransportProtocol(transport.GRPC))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kDeadlockClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kDeadlockClient struct {
	*kClient
}

func (p *kDeadlockClient) GetWaitForEntries(ctx context.Context, Req *deadlock.WaitForEntriesRequest, callOptions ...callopt.Option) (r *deadlock.WaitForEntriesResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetWaitForEntries(ctx, Req)
}

func (p *kDeadlockClient) Detect(ctx context.Context, callOptions ...callopt.Option) (stream Deadlock_DetectClient, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Detect(ctx)
}
